steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/mythical-module-348315/stats-models", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/mythical-module-348315/stats-models"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "stats-models",
        "--image",
        "gcr.io/mythical-module-348315/stats-models",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--port",
        "8080",
      ]
images:
  - gcr.io/mythical-module-348315/stats-models
